version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: devmeetups
      MYSQL_DATABASE: devmeetups
      MYSQL_USER: devmeetups
      MYSQL_PASSWORD: devmeetups
    ports:
      - "3310:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
